name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Dependices
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Run Test
        run: npm run test

      - name: Report Coverage
        uses: codecov/codecov-action@v2
